<a href="https://colab.research.google.com/github/MuhammadAasim2025/data-science-w1/blob/main/WIA1007_T3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

# 1. Create a numpy array of size 2 x 2
a=np.array([[1,2],[3,4]])
print (a)


[[1 2]
 [3 4]]


In [5]:
#2. Create a random numpy array of size 3 x 4

b=np.random.rand(3,4)
print (b)

[[0.43621583 0.38387126 0.27132438 0.95752126]
 [0.93474635 0.20631561 0.38922066 0.96586029]
 [0.72654326 0.20439335 0.40448966 0.17110907]]


In [8]:
#3. Create a numpy array of ones and a numpy array of zeroes

c=np.full((3,3),1)

d=np.full((4,3),0)

print("array of ones: \n",c)
print("array of zeroes: \n",d)

array of ones: 
 [[1 1 1]
 [1 1 1]
 [1 1 1]]
array of zeroes: 
 [[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [11]:
#4. Create a random numpy array of size 6x3 and transpose it

e=np.random.randint(10,50,size=(6,3))

print("original 6x3 array: \n",e)

e_tranpose=np.transpose(e)
print("transposed 3x6 array: \n",e_tranpose)

original 6x3 array: 
 [[25 13 24]
 [39 39 47]
 [20 11 13]
 [12 11 27]
 [37 24 14]
 [29 35 47]]
transposed 3x6 array: 
 [[25 39 20 12 37 29]
 [13 39 11 11 24 35]
 [24 47 13 27 14 47]]


In [13]:
#5. Create two random numpy array of size n x p and p x m and then compute the dot product

n,p,m=2,3,4

a1=np.random.randint(10,50,size=(n,p))
b1=np.random.randint(10,50,size=(p,m))

print("array 1: \n",a1)
print("array 2: \n",b1)

result=np.dot(a1,b1)
print("dot product: \n",result)

array 1: 
 [[45 18 17]
 [23 19 28]]
array 2: 
 [[46 49 34 31]
 [47 49 11 26]
 [25 12 22 38]]
dot product: 
 [[3341 3291 2102 2509]
 [2651 2394 1607 2271]]
